#!/bin/bash

# Create dir for files
mkdir /var/www/$1

# Read config info from file
fileData=$(<host-config.conf)

# Replace %name% with given argument
hostData="${fileData//%name%/$1}"

# Create config for apache2 server
echo -e $hostData | sudo tee /etc/apache2/sites-available/$1.conf > /dev/null

# Enable site from created config
sudo a2ensite $1.conf

read -p "IP host (127.0.0.1): " ip
if [ -z "$ip" ];	then
		ip=127.0.0.1
fi

# Append /etc/hosts
sudo sed -i "3i $ip\t$1" /etc/hosts

# Restart apache2
sudo service apache2 restart
